# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: On est pas des machines
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Salut, je suis Alexis Bauchu, et je suis un programmeur
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abauchu.net" # the base hostname & protocol for your site
twitter_username: abauchu
github_username:  Albob

# Build settings
markdown: kramdown

# Overridable
# github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate

# Not Overridable
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
    noscript: false
